export const TOOL_CATEGORIES = [
  {
    id: "organize",
    label: "Organize PDF",
    color: "#e63946",
    tools: [
      {
        id: "merge",
        label: "Merge PDF",
        icon: "⊕",
        desc: "Combine multiple PDFs into one file",
        endpoint: "/merge",
        multiFile: true,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "split",
        label: "Split PDF",
        icon: "✂",
        desc: "Extract specific pages from a PDF",
        endpoint: "/split",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "pages", label: "Select the pages to extract", type: "pageSelect", placeholder: "" }],
      },
      {
        id: "reorder",
        label: "Organize Pages",
        icon: "⇅",
        desc: "Reorder pages in a PDF",
        endpoint: "/reorder",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "order", label: "Drag pages to reorder them", type: "pageReorder", placeholder: "" }],
      },
      {
        id: "remove-pages",
        label: "Remove Pages",
        icon: "🗑",
        desc: "Delete specific pages from a PDF",
        endpoint: "/remove-pages",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "pages", label: "Select the pages to remove", type: "pageSelect", placeholder: "" }],
      },
      {
        id: "rotate",
        label: "Rotate PDF",
        icon: "↻",
        desc: "Rotate pages 90°, 180° or 270°",
        endpoint: "/rotate",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          {
            name: "angle",
            label: "Rotation angle",
            type: "select",
            options: [
              { value: "90", label: "90° clockwise" },
              { value: "180", label: "180°" },
              { value: "270", label: "270° (90° counter-clockwise)" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "optimize",
    label: "Optimize PDF",
    color: "#2a9d8f",
    tools: [
      {
        id: "compress",
        label: "Compress PDF",
        icon: "⊞",
        desc: "Reduce PDF file size while preserving quality",
        endpoint: "/compress",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "crop",
        label: "Crop PDF",
        icon: "⊡",
        desc: "Crop page margins and define content area",
        endpoint: "/crop",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          { name: "x1", label: "Left (x1)", type: "number", placeholder: "0" },
          { name: "y1", label: "Top (y1)", type: "number", placeholder: "0" },
          { name: "x2", label: "Right (x2)", type: "number", placeholder: "595" },
          { name: "y2", label: "Bottom (y2)", type: "number", placeholder: "842" },
        ],
      },
      {
        id: "page-numbers",
        label: "Add Page Numbers",
        icon: "#",
        desc: "Insert page numbers into your PDF",
        endpoint: "/page-numbers",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          {
            name: "position",
            label: "Position",
            type: "select",
            options: [
              { value: "bottom-center", label: "Bottom center" },
              { value: "bottom-right", label: "Bottom right" },
              { value: "top-center", label: "Top center" },
              { value: "bottom-left", label: "Bottom left" },
            ],
          },
          { name: "start", label: "Start from page number", type: "number", placeholder: "1" },
        ],
      },
    ],
  },
  {
    id: "security",
    label: "PDF Security",
    color: "#e9c46a",
    tools: [
      {
        id: "protect",
        label: "Protect PDF",
        icon: "🔒",
        desc: "Add password protection to your PDF",
        endpoint: "/protect",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "password", label: "Password", type: "password", placeholder: "Enter password" }],
      },
      {
        id: "unlock",
        label: "Unlock PDF",
        icon: "🔓",
        desc: "Remove password from a protected PDF",
        endpoint: "/unlock",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "password", label: "Password", type: "password", placeholder: "Enter current password" }],
      },
      {
        id: "watermark",
        label: "Watermark PDF",
        icon: "◈",
        desc: "Add text watermark to all pages",
        endpoint: "/watermark",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          { name: "text", label: "Watermark text", type: "text", placeholder: "CONFIDENTIAL" },
          { name: "opacity", label: "Opacity (0.1–1.0)", type: "number", placeholder: "0.3" },
        ],
      },
    ],
  },
  {
    id: "convert-from",
    label: "Convert from PDF",
    color: "#457b9d",
    tools: [
      {
        id: "pdf-to-word",
        label: "PDF to Word",
        icon: "W",
        desc: "Convert PDF to editable Word document",
        endpoint: "/pdf-to-word",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "pdf-to-excel",
        label: "PDF to Excel",
        icon: "X",
        desc: "Extract tables from PDF to Excel",
        endpoint: "/pdf-to-excel",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "pdf-to-pptx",
        label: "PDF to PowerPoint",
        icon: "P",
        desc: "Convert PDF pages to PowerPoint slides",
        endpoint: "/pdf-to-pptx",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "pdf-to-jpg",
        label: "PDF to JPG",
        icon: "🖼",
        desc: "Convert each PDF page to a JPG image",
        endpoint: "/pdf-to-jpg",
        multiFile: false,
        accepts: ".pdf",
        fields: [{ name: "dpi", label: "Resolution (DPI)", type: "number", placeholder: "150" }],
      },
      {
        id: "extract-text",
        label: "Extract Text",
        icon: "T",
        desc: "Extract all text content from a PDF",
        endpoint: "/extract-text",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "extract-images",
        label: "Extract Images",
        icon: "📷",
        desc: "Pull all embedded images from a PDF",
        endpoint: "/extract-images",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
    ],
  },
  {
    id: "convert-to",
    label: "Convert to PDF",
    color: "#6a4c93",
    tools: [
      {
        id: "jpg-to-pdf",
        label: "JPG to PDF",
        icon: "📄",
        desc: "Convert images to a PDF document",
        endpoint: "/jpg-to-pdf",
        multiFile: true,
        accepts: ".jpg,.jpeg,.png,.webp,.bmp",
        fields: [],
      },
      {
        id: "word-to-pdf",
        label: "Word to PDF",
        icon: "→",
        desc: "Convert .docx Word files to PDF",
        endpoint: "/word-to-pdf",
        multiFile: false,
        accepts: ".docx,.doc",
        fields: [],
      },
      {
        id: "excel-to-pdf",
        label: "Excel to PDF",
        icon: "→",
        desc: "Convert .xlsx Excel files to PDF",
        endpoint: "/excel-to-pdf",
        multiFile: false,
        accepts: ".xlsx,.xls,.ods",
        fields: [],
      },
      {
        id: "pptx-to-pdf",
        label: "PowerPoint to PDF",
        icon: "→",
        desc: "Convert .pptx presentations to PDF",
        endpoint: "/pptx-to-pdf",
        multiFile: false,
        accepts: ".pptx,.ppt",
        fields: [],
      },
      {
        id: "html-to-pdf",
        label: "HTML to PDF",
        icon: "→",
        desc: "Convert HTML files to PDF",
        endpoint: "/html-to-pdf",
        multiFile: false,
        accepts: ".html,.htm",
        fields: [],
      },
    ],
  },
  {
    id: "advanced",
    label: "Advanced Tools",
    color: "#f4856a",
    tools: [
      {
        id: "ocr",
        label: "OCR PDF",
        icon: "👁",
        desc: "Extract text from scanned PDFs using OCR",
        endpoint: "/ocr",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "redact",
        label: "Redact PDF",
        icon: "▓",
        desc: "Permanently black out sensitive text or areas — the underlying content is actually removed, not just covered",
        endpoint: "/redact",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          {
            name: "regions",
            label: "Regions to redact (JSON — page is 0-indexed, coordinates in PDF points from top-left)",
            type: "textarea",
            placeholder: '[{"page":0,"x0":100,"y0":100,"x1":300,"y1":130}]',
          },
        ],
      },
      {
        id: "edit",
        label: "Edit PDF",
        icon: "✎",
        desc: "Add text, rectangles, circles or lines directly onto a page",
        endpoint: "/edit",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          {
            name: "operations",
            label: "Edit operations (JSON — page is 0-indexed, coordinates in PDF points from top-left)",
            type: "textarea",
            placeholder: '[{"type":"text","page":0,"x":100,"y":400,"text":"Approved","font_size":20,"color":[1,0,0]}]',
          },
        ],
      },
      {
        id: "sign",
        label: "Sign PDF",
        icon: "✍",
        desc: "Stamp a signature image onto a page at a chosen position",
        endpoint: "/sign",
        multiFile: false,
        accepts: ".pdf",
        fields: [
          { name: "signature", label: "Signature image (PNG with transparent background works best)", type: "file", accepts: ".png,.jpg,.jpeg" },
          { name: "page", label: "Page number (0-indexed)", type: "number", placeholder: "0" },
          { name: "x", label: "X position (PDF points from left)", type: "number", placeholder: "100" },
          { name: "y", label: "Y position (PDF points from top)", type: "number", placeholder: "600" },
          { name: "width", label: "Signature width", type: "number", placeholder: "150" },
          { name: "height", label: "Signature height", type: "number", placeholder: "60" },
        ],
      },
      {
        id: "compare",
        label: "Compare PDF",
        icon: "⇄",
        desc: "Upload two versions of a PDF, in order (original, then revised), to get a text-diff report",
        endpoint: "/compare",
        multiFile: true,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "scan-to-pdf",
        label: "Scan to PDF",
        icon: "📷",
        desc: "Turn photos of documents into a single cleaned-up, multi-page PDF",
        endpoint: "/scan-to-pdf",
        multiFile: true,
        accepts: "image/*",
        fields: [],
      },
      {
        id: "pdf-to-pdfa",
        label: "PDF to PDF/A",
        icon: "🗄",
        desc: "Convert to the ISO PDF/A archival format for long-term preservation",
        endpoint: "/pdf-to-pdfa",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
      {
        id: "repair",
        label: "Repair PDF",
        icon: "🩹",
        desc: "Recover data from a corrupted or damaged PDF",
        endpoint: "/repair",
        multiFile: false,
        accepts: ".pdf",
        fields: [],
      },
    ],
  },
];

export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((c) => c.tools.map((t) => ({ ...t, category: c.id, color: c.color })));
